package clases;
// Generated 10-jul-2020 15:01:34 by Hibernate Tools 5.4.14.Final

/**
 * TipoPrecio generated by hbm2java
 */
public class TipoPrecio implements java.io.Serializable {

	private Integer id;
	private int precioBase;
	private int expensas;
	private int tipo;

	public TipoPrecio() {
	}

	public TipoPrecio(int precioBase, int expensas, int tipo) {
		this.precioBase = precioBase;
		this.expensas = expensas;
		this.tipo = tipo;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getPrecioBase() {
		return this.precioBase;
	}

	public void setPrecioBase(int precioBase) {
		this.precioBase = precioBase;
	}

	public int getExpensas() {
		return this.expensas;
	}

	public void setExpensas(int expensas) {
		this.expensas = expensas;
	}

	public int getTipo() {
		return this.tipo;
	}

	public void setTipo(int tipo) {
		this.tipo = tipo;
	}

}
